apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: out6j60kv-python 
  janus-idp.io/tekton: out6j60kv-python
  backstage.io/kubernetes-id: out6j60kv-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: out6j60kv-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml