apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: out6j60kv-python-gitops
  description: This is GitOps manifest for out6j60kv-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=out6j60kv-python
    backstage.io/kubernetes-id: out6j60kv-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: out6j60kv-python   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:out6j60kv-python
