apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: out6j60kv-python
  janus-idp.io/tekton: out6j60kv-python
  backstage.io/kubernetes-id: out6j60kv-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: out6j60kv-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
