apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: out6j60kv-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: out6j60kv-python 
  name: out6j60kv-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: out6j60kv-python 
